"""
Cassandra Snowflake Schema Definitions

This module contains Snowflake schema definitions for Cassandra time-series data.
Each schema defines the column names, data types, and constraints for Snowflake tables.
"""

# Sensor Readings Schema
CASSANDRA_SENSOR_READINGS_SCHEMA = {
    "SENSOR_ID": "VARCHAR(255) NOT NULL",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "SENSOR_TYPE": "VARCHAR(100)",
    "VALUE": "NUMBER(20,8)",
    "UNIT": "VARCHAR(50)",
    "QUALITY_SCORE": "NUMBER(10,4)",
    "LOCATION": "VARCHAR(255)",
    "CALIBRATION_DATE": "TIMESTAMP",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Machine Status Schema
CASSANDRA_MACHINE_STATUS_SCHEMA = {
    "MACHINE_ID": "VARCHAR(255) NOT NULL",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "OPERATOR_ID": "VARCHAR(255)",
    "STATUS": "VARCHAR(100)",
    "PREVIOUS_STATUS": "VARCHAR(100)",
    "PERFORMANCE_METRICS": "TEXT",
    "HEALTH_SCORE": "NUMBER(10,4)",
    "ACTIVE_ALERTS": "TEXT",
    "MAINTENANCE_REQUIRED": "INTEGER",
    "NEXT_MAINTENANCE_DATE": "TIMESTAMP",
    "LOCATION": "VARCHAR(255)",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Process Monitoring Schema
CASSANDRA_PROCESS_MONITORING_SCHEMA = {
    "PROCESS_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "MACHINE_ID": "VARCHAR(255)",
    "OPERATOR_ID": "VARCHAR(255)",
    "EVENT_TYPE": "VARCHAR(100)",
    "EVENT_DATA": "TEXT",
    "SEVERITY": "VARCHAR(50)",
    "PROCESS_STATUS": "VARCHAR(50)",
    "LAYER_NUMBER": "NUMBER(10,0)",
    "PROGRESS_PERCENTAGE": "NUMBER(10,4)",
    "SESSION_ID": "VARCHAR(255)",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Alert Events Schema
CASSANDRA_ALERT_EVENTS_SCHEMA = {
    "ALERT_ID": "VARCHAR(255) NOT NULL",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "SENSOR_ID": "VARCHAR(255)",
    "ALERT_TYPE": "VARCHAR(100)",
    "SEVERITY": "VARCHAR(50)",
    "TITLE": "VARCHAR(255)",
    "DESCRIPTION": "TEXT",
    "THRESHOLD_VALUE": "NUMBER(20,8)",
    "ACTUAL_VALUE": "NUMBER(20,8)",
    "TOLERANCE": "NUMBER(20,8)",
    "STATUS": "VARCHAR(50)",
    "ACKNOWLEDGED": "INTEGER",
    "ACKNOWLEDGED_BY": "VARCHAR(255)",
    "ACKNOWLEDGED_AT": "TIMESTAMP",
    "RESOLVED": "INTEGER",
    "RESOLVED_AT": "TIMESTAMP",
    "SOURCE_SYSTEM": "VARCHAR(255)",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Process Metrics Schema
CASSANDRA_PROCESS_METRICS_SCHEMA = {
    "PROCESS_ID": "VARCHAR(255) NOT NULL",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "METRIC_TYPE": "VARCHAR(100) NOT NULL",
    "METRIC_VALUE": "NUMBER(20,8)",
    "UNIT": "VARCHAR(50)",
    "QUALITY_SCORE": "NUMBER(10,4)",
    "SENSOR_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "MATERIAL_TYPE": "VARCHAR(100)"
}

# Sensor Data Schema
CASSANDRA_SENSOR_DATA_SCHEMA = {
    "SENSOR_ID": "VARCHAR(255) NOT NULL",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "SENSOR_TYPE": "VARCHAR(100)",
    "VALUE": "NUMBER(20,8)",
    "UNIT": "VARCHAR(50)",
    "SIGNAL_QUALITY": "NUMBER(10,4)",
    "ANOMALY_SCORE": "NUMBER(10,4)"
}

# Quality Metrics Schema
CASSANDRA_QUALITY_METRICS_SCHEMA = {
    "PROCESS_ID": "VARCHAR(255) NOT NULL",
    "MEASUREMENT_TYPE": "VARCHAR(100) NOT NULL",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "DENSITY": "NUMBER(20,8)",
    "SURFACE_ROUGHNESS": "NUMBER(20,8)",
    "DIMENSIONAL_ACCURACY": "NUMBER(20,8)",
    "DEFECT_COUNT": "NUMBER(10,0)",
    "QUALITY_GRADE": "VARCHAR(50)",
    "INSPECTOR_ID": "VARCHAR(255)"
}

# Material Properties Schema
CASSANDRA_MATERIAL_PROPERTIES_SCHEMA = {
    "MATERIAL_TYPE": "VARCHAR(100) NOT NULL",
    "BATCH_ID": "VARCHAR(255) NOT NULL",
    "PROPERTY_NAME": "VARCHAR(100) NOT NULL",
    "TEST_DATE": "TIMESTAMP NOT NULL",
    "PROPERTY_VALUE": "NUMBER(20,8)",
    "UNIT": "VARCHAR(50)",
    "TEST_METHOD": "VARCHAR(255)"
}

# Machine Performance Schema
CASSANDRA_MACHINE_PERFORMANCE_SCHEMA = {
    "MACHINE_ID": "VARCHAR(255) NOT NULL",
    "DATE": "DATE NOT NULL",
    "HOUR": "NUMBER(10,0) NOT NULL",
    "TOTAL_PROCESSES": "NUMBER(10,0)",
    "SUCCESSFUL_PROCESSES": "NUMBER(10,0)",
    "AVG_QUALITY_SCORE": "NUMBER(10,4)",
    "AVG_PROCESS_DURATION": "NUMBER(10,0)",
    "MAINTENANCE_EVENTS": "NUMBER(10,0)"
}

# Defect Analysis Schema
CASSANDRA_DEFECT_ANALYSIS_SCHEMA = {
    "PROCESS_ID": "VARCHAR(255) NOT NULL",
    "DEFECT_ID": "VARCHAR(255) NOT NULL",
    "DEFECT_TYPE": "VARCHAR(100)",
    "SEVERITY": "VARCHAR(50)",
    "LOCATION_X": "NUMBER(20,8)",
    "LOCATION_Y": "NUMBER(20,8)",
    "LOCATION_Z": "NUMBER(20,8)",
    "SIZE": "NUMBER(20,8)",
    "DETECTION_METHOD": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP"
}

# Analytics Aggregations Schema
CASSANDRA_ANALYTICS_AGGREGATIONS_SCHEMA = {
    "AGGREGATION_ID": "VARCHAR(255) NOT NULL",
    "TIMESTAMP": "TIMESTAMP NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "SENSOR_ID": "VARCHAR(255)",
    "AGGREGATION_TYPE": "VARCHAR(100)",
    "TIME_WINDOW": "VARCHAR(50)",
    "GRANULARITY": "VARCHAR(50)",
    "COUNT": "NUMBER(10,0)",
    "MIN_VALUE": "NUMBER(20,8)",
    "MAX_VALUE": "NUMBER(20,8)",
    "AVG_VALUE": "NUMBER(20,8)",
    "MEDIAN_VALUE": "NUMBER(20,8)",
    "STD_DEV": "NUMBER(20,8)",
    "PERCENTILES": "TEXT",
    "DATA_QUALITY_SCORE": "NUMBER(10,4)",
    "MISSING_DATA_POINTS": "NUMBER(10,0)",
    "CALCULATION_METHOD": "VARCHAR(255)",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Schema registry for Cassandra tables
CASSANDRA_SCHEMAS = {
    "sensor_readings": CASSANDRA_SENSOR_READINGS_SCHEMA,
    "machine_status": CASSANDRA_MACHINE_STATUS_SCHEMA,
    "process_monitoring": CASSANDRA_PROCESS_MONITORING_SCHEMA,
    "alert_events": CASSANDRA_ALERT_EVENTS_SCHEMA,
    "process_metrics": CASSANDRA_PROCESS_METRICS_SCHEMA,
    "sensor_data": CASSANDRA_SENSOR_DATA_SCHEMA,
    "quality_metrics": CASSANDRA_QUALITY_METRICS_SCHEMA,
    "material_properties": CASSANDRA_MATERIAL_PROPERTIES_SCHEMA,
    "machine_performance": CASSANDRA_MACHINE_PERFORMANCE_SCHEMA,
    "defect_analysis": CASSANDRA_DEFECT_ANALYSIS_SCHEMA,
    "analytics_aggregations": CASSANDRA_ANALYTICS_AGGREGATIONS_SCHEMA,
}
