"""
Elasticsearch Snowflake Schema Definitions

This module contains Snowflake schema definitions for Elasticsearch search and analytics data.
Each schema defines the column names, data types, and constraints for Snowflake tables.
"""

# PBF Process Schema
ELASTICSEARCH_PBF_PROCESS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "SF_PROCESS_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "PROCESS_PARAMETERS": "TEXT",
    "MATERIAL_INFO": "TEXT", 
    "QUALITY_METRICS": "TEXT",
    "SF_METADATA": "TEXT",
    "FULL_TEXT_SEARCH": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP"
}

# Sensor Readings Schema
ELASTICSEARCH_SENSOR_READINGS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "SENSOR_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "SENSOR_TYPE": "VARCHAR(100)",
    "SENSOR_LOCATION": "TEXT",
    "MEASUREMENT_DATA": "TEXT",
    "ENVIRONMENTAL_CONDITIONS": "TEXT",
    "QUALITY_FLAGS": "TEXT",
    "PROCESS_CONTEXT": "TEXT",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Quality Metrics Schema
ELASTICSEARCH_QUALITY_METRICS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "QUALITY_ID": "VARCHAR(255)",
    "SF_PROCESS_ID": "VARCHAR(255)",
    "SF_BUILD_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "MEASUREMENT_TYPE": "VARCHAR(100)",
    "DIMENSIONAL_METRICS": "TEXT",
    "SURFACE_QUALITY": "TEXT",
    "MECHANICAL_PROPERTIES": "TEXT",
    "DEFECT_ANALYSIS": "TEXT",
    "QUALITY_SCORES": "TEXT",
    "MEASUREMENT_CONDITIONS": "TEXT",
    "MATERIAL_PROPERTIES": "TEXT",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP"
}

# Machine Status Schema
ELASTICSEARCH_MACHINE_STATUS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "MACHINE_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "STATUS": "VARCHAR(100)",
    "OPERATIONAL_STATE": "TEXT",
    "SYSTEM_HEALTH": "TEXT",
    "LASER_SYSTEM": "TEXT",
    "BUILD_PLATFORM": "TEXT",
    "POWDER_SYSTEM": "TEXT",
    "ENVIRONMENTAL_CONDITIONS": "TEXT",
    "ALERTS_AND_WARNINGS": "TEXT",
    "PERFORMANCE_METRICS": "TEXT",
    "MAINTENANCE_INFO": "TEXT",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Build Instructions Schema
ELASTICSEARCH_BUILD_INSTRUCTIONS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "INSTRUCTION_ID": "VARCHAR(255)",
    "SF_BUILD_ID": "VARCHAR(255)",
    "SF_PROCESS_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "INSTRUCTION_TYPE": "VARCHAR(100)",
    "INSTRUCTION_CONTENT": "TEXT",
    "LAYER_INSTRUCTIONS": "TEXT",
    "MATERIAL_REQUIREMENTS": "TEXT",
    "QUALITY_REQUIREMENTS": "TEXT",
    "PROCESS_PARAMETERS": "TEXT",
    "SUPPORT_STRUCTURES": "TEXT",
    "POST_PROCESSING": "TEXT",
    "SAFETY_REQUIREMENTS": "TEXT",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP"
}

# Analytics Schema
ELASTICSEARCH_ANALYTICS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "ANALYTICS_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "ANALYSIS_TYPE": "VARCHAR(100)",
    "DATA_SOURCE": "VARCHAR(100)",
    "PERFORMANCE_METRICS": "TEXT",
    "QUALITY_ANALYTICS": "TEXT",
    "COST_ANALYTICS": "TEXT",
    "TREND_ANALYSIS": "TEXT",
    "PREDICTIVE_ANALYTICS": "TEXT",
    "ANOMALY_DETECTION": "TEXT",
    "COMPARATIVE_ANALYSIS": "TEXT",
    "KPI_METRICS": "TEXT",
    "REPORTING_METADATA": "TEXT",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP"
}

# Search Logs Schema
ELASTICSEARCH_SEARCH_LOGS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "SF_LOG_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "USER_ID": "VARCHAR(255)",
    "SESSION_ID": "VARCHAR(255)",
    "SEARCH_QUERY": "TEXT",
    "SEARCH_CONTEXT": "TEXT",
    "SEARCH_RESULTS": "TEXT",
    "USER_INTERACTION": "TEXT",
    "PERFORMANCE_METRICS": "TEXT",
    "ERROR_HANDLING": "TEXT",
    "SEARCH_ANALYTICS": "TEXT",
    "TECHNICAL_DETAILS": "TEXT",
    "SF_METADATA": "TEXT",
    "CREATED_AT": "TIMESTAMP"
}

# Schema registry for Elasticsearch indices
ELASTICSEARCH_SCHEMAS = {
    "pbf_process": ELASTICSEARCH_PBF_PROCESS_SCHEMA,
    "sensor_readings": ELASTICSEARCH_SENSOR_READINGS_SCHEMA,
    "quality_metrics": ELASTICSEARCH_QUALITY_METRICS_SCHEMA,
    "machine_status": ELASTICSEARCH_MACHINE_STATUS_SCHEMA,
    "build_instructions": ELASTICSEARCH_BUILD_INSTRUCTIONS_SCHEMA,
    "analytics": ELASTICSEARCH_ANALYTICS_SCHEMA,
    "search_logs": ELASTICSEARCH_SEARCH_LOGS_SCHEMA,
}
