"""
MongoDB Snowflake Schema Definitions

This module contains Snowflake schema definitions for MongoDB document collections.
Each schema defines the column names, data types, and constraints for Snowflake tables.
"""

# Process Images Schema
MONGODB_PROCESS_IMAGES_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(20,0)",
    "FILE_HASH": "VARCHAR(255)",
    "FILE_STATUS": "VARCHAR(50)",
    "IMAGE_WIDTH": "NUMBER(10,0)",
    "IMAGE_HEIGHT": "NUMBER(10,0)",
    "IMAGE_FORMAT": "VARCHAR(50)",
    "IMAGE_QUALITY": "VARCHAR(50)",
    "CAMERA_SETTINGS": "TEXT",
    "PROCESSING_STATUS": "VARCHAR(50)",
    "ANALYSIS_RESULTS": "TEXT",
    "DEFECTS_DETECTED": "TEXT",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# CT Scan Images Schema
MONGODB_CT_SCAN_IMAGES_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(20,0)",
    "FILE_HASH": "VARCHAR(255)",
    "FILE_STATUS": "VARCHAR(50)",
    "SCAN_PARAMETERS": "TEXT",
    "IMAGE_DIMENSIONS": "TEXT",
    "IMAGE_FORMAT": "VARCHAR(50)",
    "IMAGE_QUALITY": "TEXT",
    "PROCESSING_STATUS": "VARCHAR(50)",
    "ANALYSIS_RESULTS": "TEXT",
    "SF_SCAN_METADATA": "TEXT",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Powder Bed Images Schema
MONGODB_POWDER_BED_IMAGES_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(20,0)",
    "FILE_HASH": "VARCHAR(255)",
    "FILE_STATUS": "VARCHAR(50)",
    "IMAGE_WIDTH": "NUMBER(10,0)",
    "IMAGE_HEIGHT": "NUMBER(10,0)",
    "IMAGE_FORMAT": "VARCHAR(50)",
    "IMAGE_QUALITY": "VARCHAR(50)",
    "CAMERA_SETTINGS": "TEXT",
    "PROCESSING_STATUS": "VARCHAR(50)",
    "ANALYSIS_RESULTS": "TEXT",
    "DEFECTS_DETECTED": "TEXT",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Machine Build Files Schema
MONGODB_MACHINE_BUILD_FILES_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(20,0)",
    "FILE_HASH": "VARCHAR(255)",
    "FILE_STATUS": "VARCHAR(50)",
    "FILE_FORMAT": "VARCHAR(50)",
    "FILE_VERSION": "VARCHAR(50)",
    "BUILD_PARAMETERS": "TEXT",
    "LAYER_INFORMATION": "TEXT",
    "SUPPORT_STRUCTURES": "TEXT",
    "PROCESSING_STATUS": "VARCHAR(50)",
    "VALIDATION_RESULTS": "TEXT",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Model 3D Files Schema
MONGODB_MODEL_3D_FILES_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(20,0)",
    "FILE_HASH": "VARCHAR(255)",
    "FILE_STATUS": "VARCHAR(50)",
    "FILE_FORMAT": "VARCHAR(50)",
    "FILE_VERSION": "VARCHAR(50)",
    "MODEL_GEOMETRY": "TEXT",
    "MESH_QUALITY": "TEXT",
    "DIMENSIONS": "TEXT",
    "VOLUME": "NUMBER(10,4)",
    "SURFACE_AREA": "NUMBER(10,4)",
    "COMPLEXITY_SCORE": "NUMBER(10,4)",
    "PROCESSING_STATUS": "VARCHAR(50)",
    "VALIDATION_RESULTS": "TEXT",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Raw Sensor Data Schema
MONGODB_RAW_SENSOR_DATA_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(20,0)",
    "FILE_HASH": "VARCHAR(255)",
    "FILE_STATUS": "VARCHAR(50)",
    "SENSOR_TYPE": "VARCHAR(50)",
    "SENSOR_ID": "VARCHAR(255)",
    "DATA_FORMAT": "VARCHAR(50)",
    "SAMPLING_RATE": "NUMBER(10,2)",
    "DATA_DURATION": "NUMBER(10,2)",
    "DATA_POINTS": "NUMBER(10,0)",
    "PROCESSING_STATUS": "VARCHAR(50)",
    "DATA_QUALITY": "VARCHAR(50)",
    "CALIBRATION_INFO": "TEXT",
    "SENSOR_LOCATION": "TEXT",
    "MEASUREMENT_RANGE": "TEXT",
    "DATA_STATISTICS": "TEXT",
    "ANOMALY_DETECTION": "TEXT",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Process Logs Schema
MONGODB_PROCESS_LOGS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "LOG_LEVEL": "VARCHAR(50)",
    "LOG_SOURCE": "VARCHAR(255)",
    "LOG_MESSAGE": "TEXT",
    "LOG_TIMESTAMP": "TIMESTAMP",
    "LOG_DURATION": "NUMBER(10,4)",
    "LOG_CATEGORY": "VARCHAR(100)",
    "LOG_SEVERITY": "VARCHAR(50)",
    "ERROR_CODE": "VARCHAR(100)",
    "STACK_TRACE": "TEXT",
    "USER_ANNOTATIONS": "TEXT",
    "SYSTEM_CONTEXT": "TEXT",
    "PROCESSING_STATUS": "VARCHAR(50)",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Machine Configurations Schema
MONGODB_MACHINE_CONFIGURATIONS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "CONFIG_TYPE": "VARCHAR(100)",
    "CONFIG_VERSION": "VARCHAR(50)",
    "CONFIG_PARAMETERS": "TEXT",
    "MACHINE_SETTINGS": "TEXT",
    "PROCESS_SETTINGS": "TEXT",
    "SAFETY_SETTINGS": "TEXT",
    "CALIBRATION_DATA": "TEXT",
    "VALIDATION_RESULTS": "TEXT",
    "CONFIG_STATUS": "VARCHAR(50)",
    "ACTIVATION_DATE": "TIMESTAMP",
    "DEACTIVATION_DATE": "TIMESTAMP",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Build Instructions Schema
MONGODB_BUILD_INSTRUCTIONS_SCHEMA = {
    "DOCUMENT_ID": "VARCHAR(255) NOT NULL",
    "DOCUMENT_TYPE": "VARCHAR(50)",
    "PROCESS_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "INSTRUCTION_TYPE": "VARCHAR(100)",
    "INSTRUCTION_VERSION": "VARCHAR(50)",
    "INSTRUCTION_TITLE": "VARCHAR(255)",
    "INSTRUCTION_DESCRIPTION": "TEXT",
    "PROCEDURE_STEPS": "TEXT",
    "SAFETY_PROTOCOLS": "TEXT",
    "REQUIRED_TOOLS": "TEXT",
    "QUALITY_CHECKS": "TEXT",
    "ESTIMATED_DURATION": "NUMBER(10,2)",
    "DIFFICULTY_LEVEL": "VARCHAR(50)",
    "AUTHOR": "VARCHAR(255)",
    "APPROVAL_STATUS": "VARCHAR(50)",
    "EFFECTIVE_DATE": "TIMESTAMP",
    "EXPIRATION_DATE": "TIMESTAMP",
    "SF_METADATA": "TEXT",
    "TAGS": "TEXT",
    "RELATIONSHIPS": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "VERSION": "NUMBER(10,0)"
}

# Schema registry for MongoDB collections
MONGODB_SCHEMAS = {
    "mongodb_process_images": MONGODB_PROCESS_IMAGES_SCHEMA,
    "mongodb_ct_scan_images": MONGODB_CT_SCAN_IMAGES_SCHEMA,
    "mongodb_powder_bed_images": MONGODB_POWDER_BED_IMAGES_SCHEMA,
    "mongodb_machine_build_files": MONGODB_MACHINE_BUILD_FILES_SCHEMA,
    "mongodb_model_3d_files": MONGODB_MODEL_3D_FILES_SCHEMA,
    "mongodb_raw_sensor_data": MONGODB_RAW_SENSOR_DATA_SCHEMA,
    "mongodb_process_logs": MONGODB_PROCESS_LOGS_SCHEMA,
    "mongodb_machine_configurations": MONGODB_MACHINE_CONFIGURATIONS_SCHEMA,
    "mongodb_build_instructions": MONGODB_BUILD_INSTRUCTIONS_SCHEMA,
}
