"""
Neo4j Snowflake Schema Definitions

This module contains Snowflake schema definitions for Neo4j knowledge graph data.
Each schema defines the column names, data types, and constraints for Snowflake tables.
"""

# Neo4j Nodes Schema - Comprehensive Manufacturing Graph
NEO4J_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "GRAPH_ID": "VARCHAR(255)",
    "NODE_TYPE": "VARCHAR(100)",
    "LABELS": "TEXT",
    "PROPERTIES": "TEXT",
    "SOURCE": "VARCHAR(50)",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# Neo4j Relationships Schema - Comprehensive Manufacturing Graph
NEO4J_RELATIONSHIPS_SCHEMA = {
    "SF_RELATIONSHIP_ID": "VARCHAR(255)",
    "FROM_NODE_ID": "VARCHAR(255)",
    "TO_NODE_ID": "VARCHAR(255)",
    "RELATIONSHIP_TYPE": "VARCHAR(100)",
    "PROPERTIES": "TEXT",
    "SOURCE": "VARCHAR(50)",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# Core Manufacturing Nodes Schema
NEO4J_PROCESS_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "MATERIAL_TYPE": "VARCHAR(100)",
    "QUALITY_GRADE": "VARCHAR(10)",
    "LASER_POWER": "NUMBER(10,2)",
    "SCAN_SPEED": "NUMBER(10,2)",
    "LAYER_THICKNESS": "NUMBER(10,3)",
    "DENSITY": "NUMBER(10,3)",
    "SURFACE_ROUGHNESS": "NUMBER(10,2)",
    "STATUS": "VARCHAR(50)",
    "DURATION": "NUMBER(10,0)",
    "ENERGY_CONSUMPTION": "NUMBER(10,2)",
    "POWDER_USAGE": "NUMBER(10,2)",
    "BUILD_TEMPERATURE": "NUMBER(10,2)",
    "CHAMBER_PRESSURE": "NUMBER(10,3)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Machine Nodes Schema
NEO4J_MACHINE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "MACHINE_TYPE": "VARCHAR(100)",
    "MODEL": "VARCHAR(100)",
    "STATUS": "VARCHAR(50)",
    "LOCATION": "VARCHAR(255)",
    "INSTALLATION_DATE": "DATE",
    "MAX_BUILD_VOLUME": "TEXT",
    "LASER_POWER_MAX": "NUMBER(10,2)",
    "LAYER_THICKNESS_RANGE": "TEXT",
    "ACCURACY": "NUMBER(10,3)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Part Nodes Schema
NEO4J_PART_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "PART_TYPE": "VARCHAR(100)",
    "MATERIAL_TYPE": "VARCHAR(100)",
    "DIMENSIONS": "TEXT",
    "VOLUME": "NUMBER(10,3)",
    "SURFACE_AREA": "NUMBER(10,2)",
    "WEIGHT": "NUMBER(10,3)",
    "STATUS": "VARCHAR(50)",
    "QUALITY_GRADE": "VARCHAR(10)",
    "TOLERANCE": "NUMBER(10,3)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Build Nodes Schema
NEO4J_BUILD_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "BUILD_NAME": "VARCHAR(255)",
    "STATUS": "VARCHAR(50)",
    "CREATED_DATE": "DATE",
    "COMPLETED_DATE": "DATE",
    "TOTAL_PARTS": "NUMBER(10,0)",
    "SUCCESS_RATE": "NUMBER(10,3)",
    "TOTAL_DURATION": "NUMBER(10,0)",
    "MATERIAL_USAGE": "NUMBER(10,2)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Material Nodes Schema
NEO4J_MATERIAL_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "MATERIAL_TYPE": "VARCHAR(100)",
    "PROPERTIES": "TEXT",
    "SUPPLIER": "VARCHAR(255)",
    "CERTIFICATION": "VARCHAR(100)",
    "BATCH_NUMBER": "VARCHAR(100)",
    "CONDITION": "VARCHAR(50)",
    "STORAGE_TEMPERATURE": "NUMBER(10,2)",
    "HUMIDITY": "NUMBER(10,2)",
    "METADATA": "TEXT"
}

# Quality Nodes Schema
NEO4J_QUALITY_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "GRADE": "VARCHAR(10)",
    "METRICS": "TEXT",
    "STANDARDS": "TEXT",
    "INSPECTOR": "VARCHAR(255)",
    "INSPECTION_DATE": "DATE",
    "TEST_METHOD": "VARCHAR(100)",
    "CONFIDENCE_LEVEL": "NUMBER(10,3)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Sensor Nodes Schema
NEO4J_SENSOR_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "SENSOR_ID": "VARCHAR(255)",
    "SENSOR_TYPE": "VARCHAR(100)",
    "LOCATION": "VARCHAR(255)",
    "MODEL": "VARCHAR(100)",
    "CALIBRATION_DATE": "DATE",
    "ACCURACY": "NUMBER(10,3)",
    "RANGE": "TEXT",
    "SAMPLING_RATE": "NUMBER(10,2)",
    "STATUS": "VARCHAR(50)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# User Nodes Schema
NEO4J_USER_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "USER_ID": "VARCHAR(255)",
    "USERNAME": "VARCHAR(100)",
    "NAME": "VARCHAR(255)",
    "ROLE": "VARCHAR(50)",
    "DEPARTMENT": "VARCHAR(100)",
    "EMAIL": "VARCHAR(255)",
    "PHONE": "VARCHAR(50)",
    "ACTIVE": "BOOLEAN",
    "LAST_LOGIN": "TIMESTAMP",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Image Nodes Schema
NEO4J_IMAGE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "IMAGE_ID": "VARCHAR(255)",
    "IMAGE_TYPE": "VARCHAR(100)",
    "FORMAT": "VARCHAR(50)",
    "RESOLUTION": "TEXT",
    "FILE_SIZE": "NUMBER(10,0)",
    "TIMESTAMP": "TIMESTAMP",
    "CAMERA_POSITION": "TEXT",
    "LIGHTING_CONDITIONS": "VARCHAR(100)",
    "QUALITY_SCORE": "NUMBER(10,3)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Alert Nodes Schema
NEO4J_ALERT_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "ALERT_ID": "VARCHAR(255)",
    "SEVERITY": "VARCHAR(50)",
    "STATUS": "VARCHAR(50)",
    "TIMESTAMP": "TIMESTAMP",
    "MESSAGE": "TEXT",
    "THRESHOLD": "NUMBER(10,2)",
    "ACTUAL_VALUE": "NUMBER(10,2)",
    "RESOLUTION_TIME": "NUMBER(10,0)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Thermal Image Nodes Schema
NEO4J_THERMAL_IMAGE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "THERMAL_ID": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "THERMAL_TYPE": "VARCHAR(100)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(10,0)",
    "DIMENSIONS": "TEXT",
    "FORMAT": "VARCHAR(50)",
    "TEMPERATURE_RANGE": "TEXT",
    "EMISSIVITY": "NUMBER(10,3)",
    "AMBIENT_TEMPERATURE": "NUMBER(10,2)",
    "TIMESTAMP": "TIMESTAMP",
    "CAMERA_POSITION": "TEXT",
    "DISTANCE_TO_TARGET": "NUMBER(10,2)",
    "FIELD_OF_VIEW": "TEXT",
    "THERMAL_RESOLUTION": "NUMBER(10,3)",
    "QUALITY_SCORE": "NUMBER(10,3)",
    "HOT_SPOTS_DETECTED": "TEXT",
    "COLD_SPOTS_DETECTED": "TEXT",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Process Image Nodes Schema
NEO4J_PROCESS_IMAGE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "IMAGE_ID": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "IMAGE_TYPE": "VARCHAR(100)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(10,0)",
    "DIMENSIONS": "TEXT",
    "FORMAT": "VARCHAR(50)",
    "RESOLUTION": "NUMBER(10,2)",
    "TIMESTAMP": "TIMESTAMP",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# CT Scan Image Nodes Schema
NEO4J_CT_SCAN_IMAGE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "SCAN_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "SCAN_TYPE": "VARCHAR(100)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(10,0)",
    "VOXEL_SIZE": "TEXT",
    "SCAN_RESOLUTION": "TEXT",
    "TIMESTAMP": "TIMESTAMP",
    "QUALITY_SCORE": "NUMBER(10,3)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Powder Bed Image Nodes Schema
NEO4J_POWDER_BED_IMAGE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "IMAGE_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "LAYER_NUMBER": "NUMBER(10,0)",
    "IMAGE_TYPE": "VARCHAR(100)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(10,0)",
    "DIMENSIONS": "TEXT",
    "TIMESTAMP": "TIMESTAMP",
    "POWDER_DENSITY": "NUMBER(10,3)",
    "DEFECTS_DETECTED": "TEXT",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Build File Nodes Schema
NEO4J_BUILD_FILE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "FILE_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "FILE_TYPE": "VARCHAR(100)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(10,0)",
    "FORMAT": "VARCHAR(50)",
    "VERSION": "VARCHAR(50)",
    "CHECKSUM": "VARCHAR(64)",
    "CREATED_AT": "TIMESTAMP",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Model File Nodes Schema
NEO4J_MODEL_FILE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "MODEL_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "FILE_TYPE": "VARCHAR(100)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(10,0)",
    "FORMAT": "VARCHAR(50)",
    "VERSION": "VARCHAR(50)",
    "DIMENSIONS": "TEXT",
    "VOLUME": "NUMBER(10,3)",
    "SURFACE_AREA": "NUMBER(10,2)",
    "COMPLEXITY_SCORE": "NUMBER(10,3)",
    "CREATED_AT": "TIMESTAMP",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Log File Nodes Schema
NEO4J_LOG_FILE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "LOG_ID": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "LOG_TYPE": "VARCHAR(100)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_SIZE": "NUMBER(10,0)",
    "FORMAT": "VARCHAR(50)",
    "LEVEL": "VARCHAR(50)",
    "ENTRIES_COUNT": "NUMBER(10,0)",
    "START_TIME": "TIMESTAMP",
    "END_TIME": "TIMESTAMP",
    "DURATION": "NUMBER(10,2)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Process Cache Nodes Schema
NEO4J_PROCESS_CACHE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "CACHE_ID": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "CACHE_TYPE": "VARCHAR(100)",
    "KEY": "VARCHAR(255)",
    "VALUE": "TEXT",
    "SIZE": "NUMBER(10,0)",
    "TTL": "NUMBER(10,0)",
    "CREATED_AT": "TIMESTAMP",
    "EXPIRES_AT": "TIMESTAMP",
    "ACCESS_COUNT": "NUMBER(10,0)",
    "LAST_ACCESSED": "TIMESTAMP",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Analytics Cache Nodes Schema
NEO4J_ANALYTICS_CACHE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "CACHE_ID": "VARCHAR(255)",
    "ANALYSIS_TYPE": "VARCHAR(100)",
    "CACHE_KEY": "VARCHAR(255)",
    "RESULT_DATA": "TEXT",
    "SIZE": "NUMBER(10,0)",
    "TTL": "NUMBER(10,0)",
    "CREATED_AT": "TIMESTAMP",
    "EXPIRES_AT": "TIMESTAMP",
    "COMPUTATION_TIME": "NUMBER(10,2)",
    "ACCURACY": "NUMBER(10,3)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Job Queue Nodes Schema
NEO4J_JOB_QUEUE_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "JOB_ID": "VARCHAR(255)",
    "QUEUE_NAME": "VARCHAR(100)",
    "JOB_TYPE": "VARCHAR(100)",
    "PRIORITY": "NUMBER(10,0)",
    "STATUS": "VARCHAR(50)",
    "PAYLOAD": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "RETRY_COUNT": "NUMBER(10,0)",
    "MAX_RETRIES": "NUMBER(10,0)",
    "TIMEOUT": "NUMBER(10,0)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# User Session Nodes Schema
NEO4J_USER_SESSION_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "SESSION_ID": "VARCHAR(255)",
    "USER_ID": "VARCHAR(255)",
    "SESSION_TYPE": "VARCHAR(50)",
    "STATUS": "VARCHAR(50)",
    "CREATED_AT": "TIMESTAMP",
    "LAST_ACTIVITY": "TIMESTAMP",
    "EXPIRES_AT": "TIMESTAMP",
    "IP_ADDRESS": "VARCHAR(50)",
    "USER_AGENT": "TEXT",
    "PERMISSIONS": "TEXT",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Sensor Reading Nodes Schema
NEO4J_SENSOR_READING_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "READING_ID": "VARCHAR(255)",
    "SENSOR_ID": "VARCHAR(255)",
    "READING_TYPE": "VARCHAR(100)",
    "VALUE": "NUMBER(10,3)",
    "UNIT": "VARCHAR(50)",
    "TIMESTAMP": "TIMESTAMP",
    "QUALITY": "NUMBER(10,3)",
    "STATUS": "VARCHAR(50)",
    "LOCATION": "TEXT",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Process Monitoring Nodes Schema
NEO4J_PROCESS_MONITORING_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "EVENT_ID": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "EVENT_TYPE": "VARCHAR(100)",
    "SEVERITY": "VARCHAR(50)",
    "MESSAGE": "TEXT",
    "TIMESTAMP": "TIMESTAMP",
    "PARAMETERS": "TEXT",
    "STATUS": "VARCHAR(50)",
    "RESOLVED": "BOOLEAN",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Machine Status Nodes Schema
NEO4J_MACHINE_STATUS_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "STATUS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "STATUS_TYPE": "VARCHAR(100)",
    "STATUS_VALUE": "VARCHAR(100)",
    "TIMESTAMP": "TIMESTAMP",
    "DURATION": "NUMBER(10,2)",
    "REASON": "TEXT",
    "OPERATOR_ID": "VARCHAR(255)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Alert Event Nodes Schema
NEO4J_ALERT_EVENT_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "ALERT_ID": "VARCHAR(255)",
    "SOURCE_ID": "VARCHAR(255)",
    "ALERT_TYPE": "VARCHAR(100)",
    "SEVERITY": "VARCHAR(50)",
    "MESSAGE": "TEXT",
    "TIMESTAMP": "TIMESTAMP",
    "STATUS": "VARCHAR(50)",
    "ACKNOWLEDGED": "BOOLEAN",
    "RESOLVED": "BOOLEAN",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Batch Nodes Schema
NEO4J_BATCH_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "BATCH_ID": "VARCHAR(255)",
    "MATERIAL_ID": "VARCHAR(255)",
    "BATCH_NUMBER": "VARCHAR(100)",
    "SUPPLIER": "VARCHAR(255)",
    "CONDITION": "VARCHAR(100)",
    "QUANTITY": "NUMBER(10,2)",
    "UNIT": "VARCHAR(50)",
    "EXPIRY_DATE": "DATE",
    "STORAGE_LOCATION": "VARCHAR(255)",
    "QUALITY_CERTIFICATE": "VARCHAR(255)",
    "METADATA": "TEXT",
    "PROPERTIES": "VARCHAR(MAX)"
}

# Defect Nodes Schema
NEO4J_DEFECT_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "DEFECT_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "DEFECT_TYPE": "VARCHAR(100)",
    "SEVERITY": "VARCHAR(50)",
    "LOCATION": "TEXT",
    "SIZE": "NUMBER(10,3)",
    "DESCRIPTION": "TEXT",
    "DETECTED_BY": "VARCHAR(255)",
    "DETECTION_METHOD": "VARCHAR(100)",
    "TIMESTAMP": "TIMESTAMP",
    "STATUS": "VARCHAR(50)",
    "RESOLUTION": "TEXT",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Inspection Nodes Schema
NEO4J_INSPECTION_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "INSPECTION_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "INSPECTION_TYPE": "VARCHAR(100)",
    "INSPECTOR_ID": "VARCHAR(255)",
    "INSPECTION_DATE": "DATE",
    "RESULT": "VARCHAR(50)",
    "QUALITY_SCORE": "NUMBER(10,3)",
    "DEFECTS_FOUND": "NUMBER(10,0)",
    "MEASUREMENTS": "TEXT",
    "STANDARDS": "TEXT",
    "NOTES": "TEXT",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Log Nodes Schema
NEO4J_LOG_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "LOG_ID": "VARCHAR(255)",
    "SOURCE": "VARCHAR(100)",
    "LEVEL": "VARCHAR(50)",
    "MESSAGE": "TEXT",
    "TIMESTAMP": "TIMESTAMP",
    "PROCESS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "USER_ID": "VARCHAR(255)",
    "CATEGORY": "VARCHAR(100)",
    "SEVERITY": "VARCHAR(50)",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Measurement Nodes Schema
NEO4J_MEASUREMENT_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "MEASUREMENT_ID": "VARCHAR(255)",
    "SENSOR_ID": "VARCHAR(255)",
    "MEASUREMENT_TYPE": "VARCHAR(100)",
    "VALUE": "NUMBER(10,3)",
    "UNIT": "VARCHAR(50)",
    "TIMESTAMP": "TIMESTAMP",
    "QUALITY": "NUMBER(10,3)",
    "STATUS": "VARCHAR(50)",
    "LOCATION": "TEXT",
    "METADATA": "TEXT",
    "PROPERTIES": "VARCHAR(MAX)"
}

# Operator Nodes Schema
NEO4J_OPERATOR_NODES_SCHEMA = {
    "SF_NODE_ID": "VARCHAR(255)",
    "OPERATOR_ID": "VARCHAR(255)",
    "NAME": "VARCHAR(255)",
    "CERTIFICATION": "VARCHAR(255)",
    "LEVEL": "VARCHAR(50)",
    "DEPARTMENT": "VARCHAR(100)",
    "SHIFT": "VARCHAR(50)",
    "EXPERIENCE_YEARS": "NUMBER(10,0)",
    "TRAINING_COMPLETED": "TEXT",
    "CERTIFICATIONS": "TEXT",
    "CONTACT_INFO": "TEXT",
    "PROPERTIES": "TEXT",
    "METADATA": "TEXT"
}

# Schema registry for Neo4j data types
NEO4J_SCHEMAS = {
    "nodes": NEO4J_NODES_SCHEMA,
    "relationships": NEO4J_RELATIONSHIPS_SCHEMA,
    "process_nodes": NEO4J_PROCESS_NODES_SCHEMA,
    "machine_nodes": NEO4J_MACHINE_NODES_SCHEMA,
    "part_nodes": NEO4J_PART_NODES_SCHEMA,
    "build_nodes": NEO4J_BUILD_NODES_SCHEMA,
    "material_nodes": NEO4J_MATERIAL_NODES_SCHEMA,
    "quality_nodes": NEO4J_QUALITY_NODES_SCHEMA,
    "sensor_nodes": NEO4J_SENSOR_NODES_SCHEMA,
    "user_nodes": NEO4J_USER_NODES_SCHEMA,
    "image_nodes": NEO4J_IMAGE_NODES_SCHEMA,
    "alert_nodes": NEO4J_ALERT_NODES_SCHEMA,
    "thermal_image_nodes": NEO4J_THERMAL_IMAGE_NODES_SCHEMA,
    "process_image_nodes": NEO4J_PROCESS_IMAGE_NODES_SCHEMA,
    "ct_scan_image_nodes": NEO4J_CT_SCAN_IMAGE_NODES_SCHEMA,
    "powder_bed_image_nodes": NEO4J_POWDER_BED_IMAGE_NODES_SCHEMA,
    "build_file_nodes": NEO4J_BUILD_FILE_NODES_SCHEMA,
    "model_file_nodes": NEO4J_MODEL_FILE_NODES_SCHEMA,
    "log_file_nodes": NEO4J_LOG_FILE_NODES_SCHEMA,
    "process_cache_nodes": NEO4J_PROCESS_CACHE_NODES_SCHEMA,
    "analytics_cache_nodes": NEO4J_ANALYTICS_CACHE_NODES_SCHEMA,
    "job_queue_nodes": NEO4J_JOB_QUEUE_NODES_SCHEMA,
    "user_session_nodes": NEO4J_USER_SESSION_NODES_SCHEMA,
    "sensor_reading_nodes": NEO4J_SENSOR_READING_NODES_SCHEMA,
    "process_monitoring_nodes": NEO4J_PROCESS_MONITORING_NODES_SCHEMA,
    "machine_status_nodes": NEO4J_MACHINE_STATUS_NODES_SCHEMA,
    "alert_event_nodes": NEO4J_ALERT_EVENT_NODES_SCHEMA,
    "batch_nodes": NEO4J_BATCH_NODES_SCHEMA,
    "defect_nodes": NEO4J_DEFECT_NODES_SCHEMA,
    "inspection_nodes": NEO4J_INSPECTION_NODES_SCHEMA,
    "log_nodes": NEO4J_LOG_NODES_SCHEMA,
    "measurement_nodes": NEO4J_MEASUREMENT_NODES_SCHEMA,
    "operator_nodes": NEO4J_OPERATOR_NODES_SCHEMA,
    # Additional mappings for debug script compatibility
    "file_nodes": NEO4J_BUILD_FILE_NODES_SCHEMA,
    "queue_nodes": NEO4J_JOB_QUEUE_NODES_SCHEMA,
    "reading_nodes": NEO4J_SENSOR_READING_NODES_SCHEMA,
    "session_nodes": NEO4J_USER_SESSION_NODES_SCHEMA,
    "event_nodes": NEO4J_PROCESS_MONITORING_NODES_SCHEMA,
}
