"""
PostgreSQL Snowflake Schema Definitions

This module contains Snowflake schema definitions for PostgreSQL data sources.
Each schema defines the column names, data types, and constraints for Snowflake tables.
"""

# PBF Process Data Schema
POSTGRESQL_PBF_PROCESS_DATA_SCHEMA = {
    "PROCESS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "BUILD_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "LAYER_NUMBER": "NUMBER(10,0)",
    "TEMPERATURE": "NUMBER(10,2)",
    "PRESSURE": "NUMBER(10,2)",
    "LASER_POWER": "NUMBER(10,2)",
    "SCAN_SPEED": "NUMBER(10,2)",
    "LAYER_HEIGHT": "NUMBER(8,3)",
    "HATCH_SPACING": "NUMBER(8,3)",
    "EXPOSURE_TIME": "NUMBER(8,2)",
    "ATMOSPHERE": "VARCHAR(20)",
    "POWDER_MATERIAL": "VARCHAR(100)",
    "POWDER_BATCH_ID": "VARCHAR(100)",
    "DENSITY": "NUMBER(5,2)",
    "SURFACE_ROUGHNESS": "NUMBER(8,2)",
    "DIMENSIONAL_ACCURACY": "NUMBER(8,3)",
    "DEFECT_COUNT": "NUMBER(10,0)",
    "PROCESS_PARAMETERS": "TEXT",
    "SF_METADATA": "TEXT"
}

# Powder Bed Data Schema
POSTGRESQL_POWDER_BED_DATA_SCHEMA = {
    "BED_ID": "VARCHAR(255) NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "LAYER_NUMBER": "NUMBER(10,0)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "IMAGE_ID": "VARCHAR(100)",
    "CAMERA_ID": "VARCHAR(50)",
    "IMAGE_FORMAT": "VARCHAR(10)",
    "RESOLUTION": "VARCHAR(20)",
    "FILE_SIZE": "NUMBER(20,0)",
    "FILE_PATH": "VARCHAR(500)",
    "EXPOSURE_TIME": "NUMBER(8,3)",
    "APERTURE": "NUMBER(4,1)",
    "ISO": "NUMBER(10,0)",
    "WHITE_BALANCE": "VARCHAR(50)",
    "LIGHTING_CONDITIONS": "VARCHAR(100)",
    "MATERIAL_TYPE": "VARCHAR(100)",
    "PARTICLE_SIZE_D10": "NUMBER(8,2)",
    "PARTICLE_SIZE_D50": "NUMBER(8,2)",
    "PARTICLE_SIZE_D90": "NUMBER(8,2)",
    "PARTICLE_SIZE_SPAN": "NUMBER(8,4)",
    "POWDER_DENSITY": "NUMBER(6,3)",
    "FLOWABILITY": "NUMBER(5,2)",
    "MOISTURE_CONTENT": "NUMBER(5,2)",
    "UNIFORMITY_SCORE": "NUMBER(5,2)",
    "COVERAGE_PERCENTAGE": "NUMBER(5,2)",
    "THICKNESS_CONSISTENCY": "NUMBER(5,2)",
    "SURFACE_ROUGHNESS": "NUMBER(8,2)",
    "DENSITY_VARIATION": "NUMBER(6,4)",
    "DEFECT_DENSITY": "NUMBER(10,4)",
    "BRIGHTNESS": "NUMBER(6,2)",
    "CONTRAST": "NUMBER(10,4)",
    "SHARPNESS": "NUMBER(10,4)",
    "NOISE_LEVEL": "NUMBER(10,4)",
    "RED_CHANNEL": "NUMBER(6,2)",
    "GREEN_CHANNEL": "NUMBER(6,2)",
    "BLUE_CHANNEL": "NUMBER(6,2)",
    "TEXTURE_HOMOGENEITY": "NUMBER(6,4)",
    "TEXTURE_CONTRAST": "NUMBER(10,4)",
    "TEXTURE_ENERGY": "NUMBER(6,4)",
    "TEXTURE_ENTROPY": "NUMBER(10,4)",
    "DEFECTS_DETECTED": "NUMBER(1,0)",
    "DEFECT_COUNT": "NUMBER(10,0)",
    "OVERALL_QUALITY_ASSESSMENT": "VARCHAR(20)",
    "AMBIENT_TEMPERATURE": "NUMBER(8,2)",
    "RELATIVE_HUMIDITY": "NUMBER(5,2)",
    "ATMOSPHERIC_PRESSURE": "NUMBER(8,2)",
    "VIBRATION_LEVEL": "NUMBER(10,6)",
    "PROCESSING_STATUS": "VARCHAR(20)",
    "SF_METADATA": "TEXT"
}

# CT Scan Data Schema
POSTGRESQL_CT_SCAN_DATA_SCHEMA = {
    "SCAN_ID": "VARCHAR(255) NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "PART_ID": "VARCHAR(255)",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "SCAN_TYPE": "VARCHAR(30)",
    "PROCESSING_STATUS": "VARCHAR(20)",
    "VOLTAGE": "NUMBER(8,2)",
    "CURRENT_AMPERAGE": "NUMBER(8,2)",
    "EXPOSURE_TIME": "NUMBER(8,3)",
    "NUMBER_OF_PROJECTIONS": "NUMBER(10,0)",
    "DETECTOR_RESOLUTION": "VARCHAR(20)",
    "VOXEL_SIZE": "NUMBER(8,2)",
    "SCAN_DURATION": "NUMBER(8,2)",
    "FILE_PATH": "VARCHAR(500)",
    "FILE_FORMAT": "VARCHAR(10)",
    "FILE_SIZE": "NUMBER(20,0)",
    "COMPRESSION": "VARCHAR(10)",
    "CHECKSUM": "VARCHAR(64)",
    "IMAGE_WIDTH": "NUMBER(10,0)",
    "IMAGE_HEIGHT": "NUMBER(10,0)",
    "IMAGE_DEPTH": "NUMBER(10,0)",
    "PHYSICAL_WIDTH": "NUMBER(10,3)",
    "PHYSICAL_HEIGHT": "NUMBER(10,3)",
    "PHYSICAL_DEPTH": "NUMBER(10,3)",
    "CONTRAST_TO_NOISE_RATIO": "NUMBER(10,4)",
    "SIGNAL_TO_NOISE_RATIO": "NUMBER(10,4)",
    "SPATIAL_RESOLUTION": "NUMBER(10,4)",
    "UNIFORMITY": "NUMBER(5,2)",
    "ARTIFACTS_DETECTED": "NUMBER(1,0)",
    "ARTIFACT_SEVERITY": "VARCHAR(10)",
    "TOTAL_DEFECTS": "NUMBER(10,0)",
    "OVERALL_QUALITY_SCORE": "NUMBER(5,2)",
    "ACCEPTANCE_STATUS": "VARCHAR(20)",
    "DIMENSIONAL_ACCURACY": "NUMBER(5,2)",
    "SF_PROCESSING_METADATA": "TEXT",
    "SF_METADATA": "TEXT"
}

# ISPM Monitoring Data Schema
POSTGRESQL_ISPM_MONITORING_DATA_SCHEMA = {
    "MONITORING_ID": "VARCHAR(255) NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "SENSOR_ID": "VARCHAR(50)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "SENSOR_TYPE": "VARCHAR(20)",
    "SENSOR_LOCATION_X": "NUMBER(10,3)",
    "SENSOR_LOCATION_Y": "NUMBER(10,3)",
    "SENSOR_LOCATION_Z": "NUMBER(10,3)",
    "MEASUREMENT_VALUE": "NUMBER(15,6)",
    "UNIT": "VARCHAR(20)",
    "MEASUREMENT_RANGE_MIN": "NUMBER(15,6)",
    "MEASUREMENT_RANGE_MAX": "NUMBER(15,6)",
    "MEASUREMENT_ACCURACY": "NUMBER(10,6)",
    "SAMPLING_RATE": "NUMBER(10,2)",
    "SIGNAL_QUALITY": "VARCHAR(10)",
    "NOISE_LEVEL": "NUMBER(10,6)",
    "CALIBRATION_STATUS": "NUMBER(1,0)",
    "LAST_CALIBRATION_DATE": "TIMESTAMP",
    "AMBIENT_TEMPERATURE": "NUMBER(8,2)",
    "RELATIVE_HUMIDITY": "NUMBER(5,2)",
    "VIBRATION_LEVEL": "NUMBER(10,6)",
    "ANOMALY_DETECTED": "NUMBER(1,0)",
    "ANOMALY_TYPE": "VARCHAR(100)",
    "ANOMALY_SEVERITY": "VARCHAR(10)",
    "RAW_DATA": "TEXT",
    "PROCESSED_DATA": "TEXT",
    "SF_METADATA": "TEXT"
}

# Powder Bed Defects Schema
POSTGRESQL_POWDER_BED_DEFECTS_SCHEMA = {
    "DEFECT_ID": "VARCHAR(100) NOT NULL",
    "BED_ID": "VARCHAR(100)",
    "DEFECT_TYPE": "VARCHAR(30)",
    "X_COORDINATE": "NUMBER(10,3)",
    "Y_COORDINATE": "NUMBER(10,3)",
    "AREA": "NUMBER(10,3)",
    "SEVERITY": "VARCHAR(10)",
    "CONFIDENCE_SCORE": "NUMBER(5,2)",
    "CREATED_AT": "TIMESTAMP"
}

# CT Scan Defect Types Schema
POSTGRESQL_CT_SCAN_DEFECT_TYPES_SCHEMA = {
    "DEFECT_TYPE_ID": "VARCHAR(255) NOT NULL",
    "SCAN_ID": "VARCHAR(100)",
    "DEFECT_TYPE": "VARCHAR(30)",
    "DEFECT_COUNT": "NUMBER(10,0)",
    "AVERAGE_SIZE": "NUMBER(10,3)",
    "MAX_SIZE": "NUMBER(10,3)",
    "SEVERITY": "VARCHAR(10)",
    "CREATED_AT": "TIMESTAMP"
}

# PBF Process Statistics Schema
POSTGRESQL_PBF_PROCESS_STATISTICS_SCHEMA = {
    "STATISTICS_ID": "VARCHAR(255) NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "STATISTIC_TYPE": "VARCHAR(50)",
    "STATISTIC_VALUE": "NUMBER(20,6)",
    "STATISTIC_UNIT": "VARCHAR(20)",
    "CALCULATION_METHOD": "VARCHAR(100)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "SF_METADATA": "TEXT"
}

# Powder Bed Statistics Schema
POSTGRESQL_POWDER_BED_STATISTICS_SCHEMA = {
    "STATISTICS_ID": "VARCHAR(255) NOT NULL",
    "BED_ID": "VARCHAR(255)",
    "STATISTIC_TYPE": "VARCHAR(50)",
    "STATISTIC_VALUE": "NUMBER(20,6)",
    "STATISTIC_UNIT": "VARCHAR(20)",
    "CALCULATION_METHOD": "VARCHAR(100)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "SF_METADATA": "TEXT"
}

# CT Scan Dimensional Measurements Schema
POSTGRESQL_CT_SCAN_DIMENSIONAL_MEASUREMENTS_SCHEMA = {
    "MEASUREMENT_ID": "VARCHAR(255) NOT NULL",
    "SCAN_ID": "VARCHAR(255)",
    "MEASUREMENT_TYPE": "VARCHAR(50)",
    "MEASUREMENT_VALUE": "NUMBER(20,6)",
    "MEASUREMENT_UNIT": "VARCHAR(20)",
    "MEASUREMENT_METHOD": "VARCHAR(100)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "SF_METADATA": "TEXT"
}

# CT Scan Statistics Schema
POSTGRESQL_CT_SCAN_STATISTICS_SCHEMA = {
    "STATISTICS_ID": "VARCHAR(255) NOT NULL",
    "SCAN_ID": "VARCHAR(255)",
    "STATISTIC_TYPE": "VARCHAR(50)",
    "STATISTIC_VALUE": "NUMBER(20,6)",
    "STATISTIC_UNIT": "VARCHAR(20)",
    "CALCULATION_METHOD": "VARCHAR(100)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "SF_METADATA": "TEXT"
}

# ISPM Sensor Statistics Schema
POSTGRESQL_ISPM_SENSOR_STATISTICS_SCHEMA = {
    "STATISTICS_ID": "VARCHAR(255) NOT NULL",
    "SENSOR_ID": "VARCHAR(255)",
    "STATISTIC_TYPE": "VARCHAR(50)",
    "STATISTIC_VALUE": "NUMBER(20,6)",
    "STATISTIC_UNIT": "VARCHAR(20)",
    "CALCULATION_METHOD": "VARCHAR(100)",
    "TIMESTAMP": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "SF_METADATA": "TEXT"
}

# Schema registry for PostgreSQL tables
POSTGRESQL_SCHEMAS = {
    "pbf_process_data": POSTGRESQL_PBF_PROCESS_DATA_SCHEMA,
    "powder_bed_data": POSTGRESQL_POWDER_BED_DATA_SCHEMA,
    "ct_scan_data": POSTGRESQL_CT_SCAN_DATA_SCHEMA,
    "ispm_monitoring_data": POSTGRESQL_ISPM_MONITORING_DATA_SCHEMA,
    "powder_bed_defects": POSTGRESQL_POWDER_BED_DEFECTS_SCHEMA,
    "ct_scan_defect_types": POSTGRESQL_CT_SCAN_DEFECT_TYPES_SCHEMA,
    "pbf_process_statistics": POSTGRESQL_PBF_PROCESS_STATISTICS_SCHEMA,
    "powder_bed_statistics": POSTGRESQL_POWDER_BED_STATISTICS_SCHEMA,
    "ct_scan_dimensional_measurements": POSTGRESQL_CT_SCAN_DIMENSIONAL_MEASUREMENTS_SCHEMA,
    "ct_scan_statistics": POSTGRESQL_CT_SCAN_STATISTICS_SCHEMA,
    "ispm_sensor_statistics": POSTGRESQL_ISPM_SENSOR_STATISTICS_SCHEMA,
}
