"""
Redis Snowflake Schema Definitions

This module contains Snowflake schema definitions for Redis cache data.
Each schema defines the column names, data types, and constraints for Snowflake tables.
"""

# Process Cache Schema
REDIS_PROCESS_CACHE_SCHEMA = {
    "SF_CACHE_KEY": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "CACHE_TYPE": "VARCHAR(100)",
    "DATA_TYPE": "VARCHAR(50)",
    "LASER_POWER": "VARCHAR(100)",
    "SCAN_SPEED": "VARCHAR(100)",
    "LAYER_THICKNESS": "VARCHAR(100)",
    "HATCH_SPACING": "VARCHAR(100)",
    "BUILD_PLATE_TEMPERATURE": "VARCHAR(100)",
    "STATUS": "VARCHAR(50)",
    "DENSITY": "VARCHAR(100)",
    "SURFACE_ROUGHNESS": "VARCHAR(100)",
    "DIMENSIONAL_ACCURACY": "VARCHAR(100)",
    "DEFECT_COUNT": "VARCHAR(100)",
    "TTL": "INTEGER",
    "HIT_COUNT": "INTEGER",
    "LAST_ACCESSED": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# Machine Status Cache Schema
REDIS_MACHINE_STATUS_CACHE_SCHEMA = {
    "SF_CACHE_KEY": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "STATUS_TYPE": "VARCHAR(100)",
    "STATUS_VALUE": "VARCHAR(255)",
    "OPERATOR_ID": "VARCHAR(255)",
    "HEALTH_SCORE": "VARCHAR(100)",
    "MAINTENANCE_STATUS": "VARCHAR(100)",
    "PERFORMANCE_METRICS": "TEXT",
    "ACTIVE_ALERTS": "TEXT",
    "TTL": "INTEGER",
    "HIT_COUNT": "INTEGER",
    "LAST_ACCESSED": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# Sensor Readings Cache Schema
REDIS_SENSOR_READINGS_CACHE_SCHEMA = {
    "SF_CACHE_KEY": "VARCHAR(255)",
    "SENSOR_ID": "VARCHAR(255)",
    "PROCESS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "SENSOR_TYPE": "VARCHAR(100)",
    "DATA_TYPE": "VARCHAR(50)",
    "VALUE": "VARCHAR(100)",
    "TIMESTAMP": "VARCHAR(100)",
    "UNIT": "VARCHAR(50)",
    "QUALITY_SCORE": "VARCHAR(100)",
    "HISTORY_COUNT": "INTEGER",
    "ALERT_COUNT": "INTEGER",
    "TTL": "INTEGER",
    "HIT_COUNT": "INTEGER",
    "LAST_ACCESSED": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# Analytics Cache Schema
REDIS_ANALYTICS_CACHE_SCHEMA = {
    "SF_CACHE_KEY": "VARCHAR(255)",
    "ANALYTICS_TYPE": "VARCHAR(100)",
    "ANALYSIS_ID": "VARCHAR(255)",
    "DATA_TYPE": "VARCHAR(50)",
    "QUALITY_TRENDS": "TEXT",
    "AVG_QUALITY": "VARCHAR(100)",
    "TOTAL_PROCESSES": "VARCHAR(100)",
    "SUCCESS_RATE": "VARCHAR(100)",
    "AVG_DURATION": "VARCHAR(100)",
    "DEFECT_PATTERNS": "TEXT",
    "TTL": "INTEGER",
    "HIT_COUNT": "INTEGER",
    "LAST_ACCESSED": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# Job Queue Items Schema
REDIS_JOB_QUEUE_ITEMS_SCHEMA = {
    "JOB_ID": "VARCHAR(255) NOT NULL",
    "PROCESS_ID": "VARCHAR(255)",
    "MACHINE_ID": "VARCHAR(255)",
    "SF_USER_ID": "VARCHAR(255)",
    "JOB_TYPE": "VARCHAR(100)",
    "JOB_STATUS": "VARCHAR(50)",
    "PRIORITY": "INTEGER",
    "QUEUE_DATA": "TEXT",
    "RETRY_COUNT": "INTEGER",
    "MAX_RETRIES": "INTEGER",
    "ERROR_MESSAGE": "TEXT",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "SCHEDULED_AT": "TIMESTAMP",
    "COMPLETED_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# User Sessions Schema
REDIS_USER_SESSIONS_SCHEMA = {
    "SESSION_ID": "VARCHAR(255) NOT NULL",
    "SF_USER_ID": "VARCHAR(255)",
    "USERNAME": "VARCHAR(255)",
    "ROLE": "VARCHAR(100)",
    "PERMISSIONS": "TEXT",
    "SF_DASHBOARD_LAYOUT": "VARCHAR(255)",
    "DEFAULT_FILTERS": "TEXT",
    "NOTIFICATION_SETTINGS": "TEXT",
    "TTL": "INTEGER",
    "LAST_ACTIVITY": "TIMESTAMP",
    "CREATED_AT": "TIMESTAMP",
    "UPDATED_AT": "TIMESTAMP",
    "EXPIRES_AT": "TIMESTAMP",
    "METADATA": "TEXT"
}

# Schema registry for Redis cache types
REDIS_SCHEMAS = {
    "process_cache": REDIS_PROCESS_CACHE_SCHEMA,
    "machine_status_cache": REDIS_MACHINE_STATUS_CACHE_SCHEMA,
    "sensor_readings_cache": REDIS_SENSOR_READINGS_CACHE_SCHEMA,
    "analytics_cache": REDIS_ANALYTICS_CACHE_SCHEMA,
    "job_queue_items": REDIS_JOB_QUEUE_ITEMS_SCHEMA,
    "user_sessions": REDIS_USER_SESSIONS_SCHEMA,
}
